Blueprint updates
craftercms/react-blueprint pull request #2
Opened 2023-10-30 18:49 UTC by jvega190

- Fix logo image rendering
- Disable image spinning when editMode is on
- Add prettier script
- Update image datasources for image-picker and rte controls

2023-10-30 18:49 UTC, jvega190 commented
@rart ^

2023-11-01 14:07 UTC, rart approved these changes

2023-11-01 14:09 UTC, sumerjabri requested changes
Please update the craftercms-plugin.yaml to update the blueprint version and the compatibility matrix.

2023-11-02 06:51 UTC, rart approved these changes

2023-11-02 20:09 UTC, sumerjabri requested changes
CC @rart

2023-11-02 20:09 UTC, sumerjabri commented on craftercms-plugin.yaml
> +    patch: 2
Is this not compatible with 4.1.3-SNAPSHOT, 4.2.0-SNAPSHOT?

2023-11-07 14:27 UTC, sumerjabri approved these changes

2023-11-07 14:27 UTC, merged